# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_4(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1066)
    self.driver.find_element(By.LINK_TEXT, "Your profile").click()
    self.driver.find_element(By.LINK_TEXT, "Change password").click()
    self.driver.find_element(By.NAME, "oldpassword").click()
    self.driver.find_element(By.NAME, "oldpassword").send_keys("Mail15")
    self.driver.find_element(By.ID, "newpassword").click()
    self.driver.find_element(By.ID, "newpassword").send_keys("Mail16")
    self.driver.find_element(By.ID, "cpassword").click()
    self.driver.find_element(By.ID, "cpassword").send_keys("Mail16")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
  
