# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test001():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_001(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(924, 1050)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("sample@example.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("sample")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    self.driver.find_element(By.ID, "itemImage").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(2) td:nth-child(2) #itemImage").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.LINK_TEXT, "CART 3").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > #itemName > a").click()
    self.driver.find_element(By.LINK_TEXT, "CART 2").click()
    self.driver.find_element(By.LINK_TEXT, "Remove").click()
    self.driver.find_element(By.LINK_TEXT, "CART 0").click()
  
